name: "Start react CI pipeline"
on:
    push:
        branches:
            - main
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: "Setup NodeJS"
              uses: actions/setup-node@v4
              with:
                node-version: 21
            #   run: sudo apt install node -y
            
            - name: "Check node version"
              run: node --version

            - name: "Clone the repository"
              uses: actions/checkout@v2 

            - name: "Checking the directories"
              run: ls -lrt github_actions2/

            - name: "Install dependencies"
              run: sudo npm install